python_requirement(
    name='common_utils_requirements',
    requirements=[
        'pytz'
    ]
)

python_sources(
    name='common_utils',
    sources=[
        'src/**'
    ],
    dependencies=[
        ':common_utils_requirements'
    ]
)
