python_requirement(
    name='db_requirements',
    requirements=[
        'pymongo',
        'python-dotenv'
    ]
)

python_sources(
    name='mongoose_db',
    sources=[
        'src/**'
    ],
    dependencies=[
        ':db_requirements'
    ]
)
