python_requirement(
    name='limiter_requirements',
    requirements=[
        'slowapi'
    ]
)

python_sources(
    name='limiter_util',
    sources=[
        'src/**'
    ],
    dependencies=[
        ':limiter_requirements'
    ]
)
