python_requirement(
    name='logger_requirements',
    requirements=[
        'pymsteams'
    ]
)

python_sources(
    name='logger_util',
    sources=[
        'src/**'
    ],
    dependencies=[
        ':logger_requirements'
    ]
)
